name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pnpm
        run: corepack enable

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: "*/pnpm-lock.yaml"

      - name: Install dependencies
        run: |
          cd whitewash
          pnpm i
          cd ..
          cd the-operation
          deno install

      - name: Run lint check on whitewash
        run: cd whitewash && pnpm lint-check

      - name: Run lint check on the-operation
        run: cd the-operation && deno run lint-check
