name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'pnpm'
      
      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Run lint check on whitewash
        run: cd whitewash && pnpm lint-check

      - name: Run lint check on the-operation
        run: cd the-operation && deno run lint-check
