type iconProps = {
  icon:
    | "icon-alarm"
    | "icon-bakrom-pc"
    | "icon-bil"
    | "icon-bruker"
    | "icon-butikk"
    | "icon-e-pakkseddel"
    | "icon-faktura"
    | "icon-full-varetelling"
    | "icon-graf-1"
    | "icon-graf-2"
    | "icon-hake"
    | "icon-handholdt-printer"
    | "icon-hovedkontor"
    | "icon-hovedkontor-flag"
    | "icon-ht"
    | "icon-ipad"
    | "icon-iphone"
    | "icon-kamera"
    | "icon-kasse"
    | "icon-konvolutt"
    | "icon-kredittnota"
    | "icon-kunde-dame"
    | "icon-kunde-kvinne"
    | "icon-kunde-mann"
    | "icon-kunder"
    | "icon-kundereise"
    | "icon-lokasjon"
    | "icon-lukk"
    | "icon-motorsag"
    | "icon-pakkseddel"
    | "icon-penger"
    | "icon-pil-hoyre"
    | "icon-pil-venstre"
    | "icon-printer-bakrom"
    | "icon-scan-pall"
    | "icon-scan-ssscc"
    | "icon-sporsmal"
    | "icon-stopp"
    | "icon-svg-sirkel"
    | "icon-svg-sms-pa-mobil"
    | "icon-svg-soppelkasse"
    | "icon-tidsfrist"
    | "icon-tommel-opp"
    | "icon-var-filosofi"
    | "icon-varseltrekant"
}

export const Icon = ({ icon }: iconProps) => {
  return <span className={`font-icons ${icon}`} />
}
